### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [jelly-beam/verl#22]
Given that the fixes in https://github.com/jelly-beam/verl/pull/21 are required for https://github.com/erlef/rebar3_hex/pull/229, would you consider cutting a new (e.g. patch) release?

**Comment by starbelly** [comment]
Indeed.

**Comment by paulo-ferraz-oliveira** [comment]
💥

**Comment by paulo-ferraz-oliveira** [comment]
1.1.1 is out!
